// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCREs0UeY0Ac6Yvj8d2y8pfN7BY_bPyTsE',
    appId: '1:893366066306:web:928f10305c3fdaede9e89b',
    messagingSenderId: '893366066306',
    projectId: 'fooddelivery-9671b',
    authDomain: 'fooddelivery-9671b.firebaseapp.com',
    storageBucket: 'fooddelivery-9671b.appspot.com',
    measurementId: 'G-X0QYEF2Q8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABpjbVKFIgyMxB267TR8qJnQsBVxrPzg8',
    appId: '1:893366066306:android:f9a46b30f9b99f0be9e89b',
    messagingSenderId: '893366066306',
    projectId: 'fooddelivery-9671b',
    storageBucket: 'fooddelivery-9671b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-bAqwblhGHLneeHpr7cvT92s5ka7qJT8',
    appId: '1:893366066306:ios:d8585d92cb0cca90e9e89b',
    messagingSenderId: '893366066306',
    projectId: 'fooddelivery-9671b',
    storageBucket: 'fooddelivery-9671b.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-bAqwblhGHLneeHpr7cvT92s5ka7qJT8',
    appId: '1:893366066306:ios:d8585d92cb0cca90e9e89b',
    messagingSenderId: '893366066306',
    projectId: 'fooddelivery-9671b',
    storageBucket: 'fooddelivery-9671b.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCREs0UeY0Ac6Yvj8d2y8pfN7BY_bPyTsE',
    appId: '1:893366066306:web:8ba1102fa0ae6abce9e89b',
    messagingSenderId: '893366066306',
    projectId: 'fooddelivery-9671b',
    authDomain: 'fooddelivery-9671b.firebaseapp.com',
    storageBucket: 'fooddelivery-9671b.appspot.com',
    measurementId: 'G-CKNH5S76KP',
  );
}
